### ISSUE TITLE
a few bad files

### ISSUE THREAD

**Issue by macw** [TalkBank/convert-chinese#3]
The converter worked well for nearly all of the files.  However, it failed on six of them.  I am pretty sure that the problematic ones were all ones that I had attempted to convert through a web interface and maybe that thing messed up some of the encoding.  I am attaching them.  I can probably fix this by hand, but I thought it best to report this.  The error message was this:

rogs/Chinese-Chang/7/*.cha
translate: { Error
    at /usr/local/lib/node_modules/convert-chinese/node_modules/google-translate-api/index.js:116:17
    at process._tickCallback (internal/process/next_tick.js:109:7) code: 'BAD_REQUEST' }
[failed.zip](https://github.com/TalkBank/convert-chinese/files/963483/failed.zip)

**Comment by FranklinChen** [comment]
I have no idea what's going on here. I took one of the files and shrank it from the end until I hit a point at which it succeeded, but can't understand why it would fail there, since we supposedly fixed the text length problem.

**Comment by macw** [comment]
Not to worry.  This is working well enough in most cases.  I think these six went through some additional special processing that messed things up.  No sense working any more on this.  It is working well enough.

--Brian
